# Generated by Django 5.2.8 on 2025-12-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoEntrada',
        ),
    ]
