# Generated by Django 5.1.7 on 2025-12-17 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_transportadora_cnpj'),
        ('estoque', '0002_delete_produtoentrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(max_length=25)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(max_length=25)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.deposito')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produtobase')),
            ],
        ),
    ]
