# Generated by Django 5.2.8 on 2025-12-18 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_produtobase_ativo_produtobase_atualizado_em_and_more'),
        ('estoque', '0003_produtoentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtofornecedor',
            name='cnpj_fornecedor',
        ),
        migrations.RemoveField(
            model_name='produtofornecedor',
            name='nome_produto',
        ),
        migrations.AddField(
            model_name='produtofornecedor',
            name='fornecedor',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='produto_estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produtobase'),
        ),
    ]
