# Generated by Django 5.2.8 on 2025-12-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_produtobase_ativo_produtobase_atualizado_em_and_more'),
        ('estoque', '0004_remove_produtofornecedor_cnpj_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produtofornecedor',
            unique_together={('fornecedor', 'codigo_produto')},
        ),
    ]
