# Generated by Django 5.2.8 on 2025-12-21 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_produtobase_ativo_produtobase_atualizado_em_and_more'),
        ('estoque', '0004_remove_produtofornecedor_cnpj_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtofornecedor',
            name='fornecedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.fornecedor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='produtofornecedor',
            unique_together={('fornecedor', 'codigo_produto')},
        ),
    ]
