# Generated by Django 5.2.8 on 2025-12-13 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_cliente_inscricao_estadual_cliente_razao_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RegraPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, help_text='Ex: SP, RJ. Vazio = todos', max_length=2, null=True)),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Ex: 10 = +10%, -5 = -5%', max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('tabela_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='cadastros.tabelapreco')),
            ],
            options={
                'verbose_name': 'Regra de Preço',
                'verbose_name_plural': 'Regras de Preço',
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Cliente',
                'verbose_name_plural': 'Tipos de Cliente',
                'ordering': ['descricao'],
            },
        ),
        migrations.DeleteModel(
            name='TipoContribuiente',
        ),
        migrations.RenameField(
            model_name='produtobase',
            old_name='preco_venda',
            new_name='preco_base',
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.produtobase'),
        ),
        migrations.AddField(
            model_name='regrapreco',
            name='tipo_cliente',
            field=models.ForeignKey(blank=True, help_text='Ex: Atacado, Varejo. Vazio = todos', null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.tipocliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cadastros.tipocliente'),
        ),
    ]
