# Generated by Django 5.2.8 on 2025-12-13 14:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_alter_enderecocliente_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'ordering': ['nome'], 'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.RemoveField(
            model_name='produtobase',
            name='descriçao',
        ),
        migrations.AddField(
            model_name='banco',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='percentual_ajuste',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentual de ajuste futuro (0 a 100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='gera_boleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produtobase',
            name='descricao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CondicaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(help_text='Ex: À vista, 7 dias, 7/14, 30/60/90', max_length=50)),
                ('dias_vencimento', models.JSONField(help_text='Ex: [0], [7], [7,14], [30,60,90]')),
                ('ativo', models.BooleanField(default=True)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicoes', to='cadastros.formapagamento')),
            ],
            options={
                'verbose_name': 'Condição de Pagamento',
                'verbose_name_plural': 'Condições de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicao_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='cadastros.condicaopagamento'),
        ),
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('DINHEIRO', 'Caixa / Dinheiro'), ('PIX', 'Conta PIX')], max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.banco')),
            ],
        ),
        migrations.CreateModel(
            name='DescontoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, help_text='Ex: 5 = 5%', max_digits=5)),
                ('valor_minimo', models.DecimalField(decimal_places=2, help_text='Valor mínimo do pedido para ativar o desconto', max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='cadastros.cliente')),
            ],
            options={
                'verbose_name': 'Desconto por Cliente',
                'verbose_name_plural': 'Descontos por Cliente',
            },
        ),
        migrations.CreateModel(
            name='Frete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FOB', 'FOB – Cliente paga'), ('CIF', 'CIF – Empresa paga')], max_length=3)),
                ('valor_cotado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_faturado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_faturamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COTADO', 'Cotado'), ('FATURADO', 'Faturado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.transportadora')),
            ],
            options={
                'verbose_name': 'Frete',
                'verbose_name_plural': 'Fretes',
            },
        ),
        migrations.CreateModel(
            name='CTe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField()),
                ('xml', models.TextField()),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.transportadora')),
                ('frete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.frete')),
            ],
        ),
        migrations.AlterField(
            model_name='produtobase',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.grupoproduto'),
        ),
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filhos', to='cadastros.planoconta')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='produtobase',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.unidademedida'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
