# Generated by Django 5.2.8 on 2025-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_grupoproduto_unidademedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
    ]
