# Generated by Django 5.2.8 on 2025-12-14 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_alter_transportadora_cnpj'),
        ('fiscal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('negociacao', 'Em negociação'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='novo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('origem', models.CharField(choices=[('cliente', 'Cliente entrou em contato'), ('vendedor', 'Vendedor entrou em contato'), ('outro', 'Outra origem')], default='cliente', help_text='Como essa oportunidade surgiu', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente')),
                ('contato', models.ForeignKey(blank=True, help_text='Pessoa de referência do cliente para esta oportunidade', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.contato')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.PositiveIntegerField(editable=False, unique=True)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('SEPARADO', 'Separado'), ('CANCELADO', 'Cancelado'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.cliente')),
                ('forma_pagamento_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.formapagamento')),
                ('frete_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.frete')),
                ('natureza_operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.naturezaoperacao')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.oportunidade')),
                ('responsavel_aprovacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovador', to=settings.AUTH_USER_MODEL)),
                ('responsavel_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregador', to=settings.AUTH_USER_MODEL)),
                ('responsavel_separacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separador', to=settings.AUTH_USER_MODEL)),
                ('tabela_pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.tabelapreco')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(default='1', max_length=5)),
                ('chave', models.CharField(blank=True, max_length=44, null=True, unique=True)),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('AUTORIZADA', 'Autorizada'), ('CANCELADA', 'Cancelada'), ('DENEGADA', 'Denegada'), ('INUTILIZADA', 'Inutilizada')], default='AUTORIZADA', max_length=20)),
                ('xml', models.TextField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.pedido')),
            ],
        ),
    ]
