# Generated by Django 5.2.8 on 2025-12-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FecoepEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('cfop', models.CharField(max_length=10)),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('INTERNA', 'Interna')], max_length=20)),
                ('cfop_padrao', models.CharField(blank=True, max_length=10, null=True)),
                ('cst_icms', models.CharField(blank=True, max_length=5, null=True)),
                ('cst_pis', models.CharField(blank=True, max_length=5, null=True)),
                ('cst_cofins', models.CharField(blank=True, max_length=5, null=True)),
                ('movimenta_estoque', models.BooleanField(default=True)),
                ('movimenta_financeiro', models.BooleanField(default=True)),
                ('gera_nfe', models.BooleanField(default=True)),
                ('descricao_nfe', models.CharField(blank=True, max_length=200, null=True)),
                ('gera_fecoep', models.BooleanField(default=False)),
            ],
        ),
    ]
