# Generated by Django 5.2.8 on 2025-12-14 01:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0007_alter_transportadora_cnpj'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('titulo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_conta', models.CharField(choices=[('Fatura', 'Fatura'), ('Boleto', 'Boleto'), ('Pix', 'Pix')], max_length=20)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Recebida', 'Recebida'), ('Atrasada', 'Atrasada'), ('Parcial', 'Parcial')], default='Aberta', max_length=20)),
                ('vencimento', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boleto_url', models.URLField(blank=True, null=True)),
                ('charge_id', models.CharField(blank=True, max_length=40, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.cliente')),
                ('criado_por', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nfe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.nfe')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ContasPagar',
            fields=[
                ('titulo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_conta', models.CharField(choices=[('Fatura', 'Fatura'), ('Boleto', 'Boleto'), ('Pix', 'Pix')], max_length=20)),
                ('situacao', models.CharField(choices=[('Aberta', 'Aberta'), ('Paga', 'Paga'), ('Atrasada', 'Atrasada'), ('Parcial', 'Parcial')], default='Aberta', max_length=20)),
                ('dt_vencimento', models.DateField(null=True, verbose_name='Data de Vencimento')),
                ('total_titulo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Multa')),
                ('cod_banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.banco')),
                ('cod_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.fornecedor')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forma_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pagamento', models.CharField(choices=[('Fatura', 'Fatura'), ('Boleto', 'Boleto'), ('Pix', 'Pix')], max_length=20)),
                ('tipo_lancamento', models.CharField(choices=[('NORMAL', 'Normal'), ('ESTORNO', 'Estorno')], default='NORMAL', max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.contaspagar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.now)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_recebimento', models.CharField(choices=[('Fatura', 'Fatura'), ('Boleto', 'Boleto'), ('Pix', 'Pix')], max_length=20)),
                ('tipo_lancamento', models.CharField(choices=[('NORMAL', 'Normal'), ('ESTORNO', 'Estorno')], default='NORMAL', max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='financeiro.contareceber')),
                ('estorna_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estornos', to='financeiro.recebimento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
