# Generated by Django 5.2.8 on 2025-12-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_alter_transportadora_cnpj'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='pedido',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='parcela',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='pedido_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='total_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.formapagamento'),
        ),
        migrations.AlterField(
            model_name='recebimento',
            name='forma_recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.formapagamento'),
        ),
    ]
