# Generated by Django 5.2.8 on 2025-12-16 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_remove_contareceber_pedido_contareceber_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='pagamento_origem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estorno', to='financeiro.pagamento'),
        ),
    ]
