# Generated by Django 5.1.7 on 2025-12-17 00:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_pagamento_pagamento_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='data_emissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='contareceber',
            unique_together={('pedido_numero', 'parcela')},
        ),
    ]
