# Generated by Django 5.1.7 on 2025-12-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_contareceber_data_emissao_contaspagar_data_emissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contaspagar',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
