# Generated by Django 5.2.8 on 2025-12-22 16:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0008_produtobase_ativo_produtobase_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True)),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcial'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20)),
                ('valor_antecipado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompraAntecipacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecipacoes', to='compras.pedidocompra')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_recebida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.pedidocompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.produtobase')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pedido', 'produto'), name='unique_produto_por_pedido')],
            },
        ),
    ]
